import { CockpitKpis, Disruption, Port, Vessel, Voyage } from "@/types";

export const vessels: Vessel[] = [
  {
    id: "v-001",
    name: "Aurora Crest",
    imo: "9742118",
    type: "Container",
    status: "Underway",
    flag: "Marshall Islands",
    capacityTeu: 14400,
    speedKn: 18.7,
    fuelPct: 64,
    cargo: "Mixed FCL — electronics, apparel",
    originPort: "Yantian",
    destinationPort: "Rotterdam",
    etaIso: "2026-06-04T08:30:00Z",
    delayHours: 6,
    carbonIndex: 71,
    routeProgress: 58,
    speedHistory: [16.8, 17.4, 18.1, 17.9, 18.5, 18.9, 18.7]
  },
  {
    id: "v-002",
    name: "Boreal Vega",
    imo: "9802411",
    type: "Reefer",
    status: "Anchored",
    flag: "Liberia",
    capacityTeu: 2300,
    speedKn: 0,
    fuelPct: 78,
    cargo: "Chilled produce — citrus, berries",
    originPort: "Valparaiso",
    destinationPort: "Long Beach",
    etaIso: "2026-05-25T13:10:00Z",
    delayHours: 22,
    carbonIndex: 58,
    routeProgress: 92,
    speedHistory: [12.0, 11.6, 9.4, 4.2, 0, 0, 0]
  },
  {
    id: "v-003",
    name: "Cygnus Maru",
    imo: "9655027",
    type: "Container",
    status: "Loading",
    flag: "Panama",
    capacityTeu: 8200,
    speedKn: 0,
    fuelPct: 91,
    cargo: "Auto parts, machinery",
    originPort: "Yokohama",
    destinationPort: "Los Angeles",
    etaIso: "2026-06-08T19:00:00Z",
    delayHours: 0,
    carbonIndex: 64,
    routeProgress: 4,
    speedHistory: [0, 0, 0, 0, 0, 0, 0]
  },
  {
    id: "v-004",
    name: "Drava Falcon",
    imo: "9881204",
    type: "Bulk",
    status: "Underway",
    flag: "Greece",
    capacityTeu: 0,
    speedKn: 12.1,
    fuelPct: 52,
    cargo: "Iron ore — 168k DWT",
    originPort: "Port Hedland",
    destinationPort: "Qingdao",
    etaIso: "2026-05-30T05:45:00Z",
    delayHours: 2,
    carbonIndex: 82,
    routeProgress: 47,
    speedHistory: [11.4, 11.7, 12.0, 12.2, 12.0, 12.1, 12.1]
  },
  {
    id: "v-005",
    name: "Equinox Voyager",
    imo: "9710334",
    type: "Tanker",
    status: "Delayed",
    flag: "Singapore",
    capacityTeu: 0,
    speedKn: 8.3,
    fuelPct: 41,
    cargo: "Crude — 1.1M bbl",
    originPort: "Ras Tanura",
    destinationPort: "Rotterdam",
    etaIso: "2026-06-12T22:00:00Z",
    delayHours: 38,
    carbonIndex: 88,
    routeProgress: 28,
    speedHistory: [13.2, 12.6, 11.0, 9.4, 8.7, 8.1, 8.3]
  },
  {
    id: "v-006",
    name: "Fjord Beacon",
    imo: "9899012",
    type: "Container",
    status: "Discharging",
    flag: "Denmark",
    capacityTeu: 11600,
    speedKn: 0,
    fuelPct: 60,
    cargo: "Mixed FCL — retail",
    originPort: "Singapore",
    destinationPort: "Hamburg",
    etaIso: "2026-05-21T11:00:00Z",
    delayHours: 0,
    carbonIndex: 69,
    routeProgress: 100,
    speedHistory: [18.4, 18.0, 17.3, 12.1, 6.0, 1.5, 0]
  },
  {
    id: "v-007",
    name: "Glacier Tide",
    imo: "9778430",
    type: "Ro-Ro",
    status: "Underway",
    flag: "Norway",
    capacityTeu: 0,
    speedKn: 16.4,
    fuelPct: 71,
    cargo: "Vehicles — 4,200 CEU",
    originPort: "Bremerhaven",
    destinationPort: "New York",
    etaIso: "2026-05-31T17:20:00Z",
    delayHours: 0,
    carbonIndex: 67,
    routeProgress: 38,
    speedHistory: [15.9, 16.1, 16.5, 16.7, 16.4, 16.5, 16.4]
  },
  {
    id: "v-008",
    name: "Helios Strait",
    imo: "9820775",
    type: "Container",
    status: "Underway",
    flag: "Hong Kong",
    capacityTeu: 18600,
    speedKn: 19.2,
    fuelPct: 81,
    cargo: "Mixed FCL — tech, furniture",
    originPort: "Shanghai",
    destinationPort: "Felixstowe",
    etaIso: "2026-06-09T06:15:00Z",
    delayHours: 0,
    carbonIndex: 73,
    routeProgress: 22,
    speedHistory: [18.2, 18.7, 19.0, 19.3, 19.1, 19.2, 19.2]
  }
];

export const ports: Port[] = [
  {
    id: "p-001",
    name: "Singapore",
    country: "Singapore",
    unlocode: "SGSIN",
    congestion: "Heavy",
    vesselsAtAnchor: 38,
    vesselsBerthed: 64,
    avgWaitHours: 36,
    weeklyTrend: 12,
    cargoMix: "Transshipment, bunker, container",
    events: ["Heavy NE monsoon swell", "Berth 41 maintenance window"]
  },
  {
    id: "p-002",
    name: "Rotterdam",
    country: "Netherlands",
    unlocode: "NLRTM",
    congestion: "Moderate",
    vesselsAtAnchor: 14,
    vesselsBerthed: 58,
    avgWaitHours: 18,
    weeklyTrend: -6,
    cargoMix: "Container, crude, LNG",
    events: ["Maasvlakte automated quay back online"]
  },
  {
    id: "p-003",
    name: "Long Beach",
    country: "USA",
    unlocode: "USLGB",
    congestion: "Critical",
    vesselsAtAnchor: 27,
    vesselsBerthed: 31,
    avgWaitHours: 62,
    weeklyTrend: 21,
    cargoMix: "Asia → US West Coast container",
    events: ["ILWU shift overtime restrictions", "Reefer plug shortage berth 12-14"]
  },
  {
    id: "p-004",
    name: "Shanghai",
    country: "China",
    unlocode: "CNSHA",
    congestion: "Moderate",
    vesselsAtAnchor: 22,
    vesselsBerthed: 88,
    avgWaitHours: 14,
    weeklyTrend: 4,
    cargoMix: "Container, automotive, project cargo",
    events: ["Yangshan deepwater throughput +9% w/w"]
  },
  {
    id: "p-005",
    name: "Hamburg",
    country: "Germany",
    unlocode: "DEHAM",
    congestion: "Calm",
    vesselsAtAnchor: 6,
    vesselsBerthed: 24,
    avgWaitHours: 8,
    weeklyTrend: -2,
    cargoMix: "Container, project cargo",
    events: ["Inland barge backlog cleared"]
  },
  {
    id: "p-006",
    name: "Port Hedland",
    country: "Australia",
    unlocode: "AUPHE",
    congestion: "Heavy",
    vesselsAtAnchor: 19,
    vesselsBerthed: 8,
    avgWaitHours: 41,
    weeklyTrend: 8,
    cargoMix: "Iron ore export",
    events: ["Cyclone watch tier-2", "Ore export window narrowed"]
  }
];

export const voyages: Voyage[] = [
  {
    id: "vy-001",
    routeCode: "AS-EU-12",
    from: "Yantian",
    to: "Rotterdam",
    vessel: "Aurora Crest",
    departureIso: "2026-05-12T03:00:00Z",
    arrivalIso: "2026-06-04T08:30:00Z",
    distanceNm: 10620,
    status: "In transit",
    fuelTons: 2840,
    onTimeScore: 78,
    riskScore: 31
  },
  {
    id: "vy-002",
    routeCode: "SA-NA-07",
    from: "Valparaiso",
    to: "Long Beach",
    vessel: "Boreal Vega",
    departureIso: "2026-05-04T11:00:00Z",
    arrivalIso: "2026-05-25T13:10:00Z",
    distanceNm: 4880,
    status: "Diverted",
    fuelTons: 920,
    onTimeScore: 41,
    riskScore: 76
  },
  {
    id: "vy-003",
    routeCode: "AP-NA-22",
    from: "Yokohama",
    to: "Los Angeles",
    vessel: "Cygnus Maru",
    departureIso: "2026-05-22T18:00:00Z",
    arrivalIso: "2026-06-08T19:00:00Z",
    distanceNm: 4830,
    status: "Planned",
    fuelTons: 1180,
    onTimeScore: 88,
    riskScore: 22
  },
  {
    id: "vy-004",
    routeCode: "AU-CN-05",
    from: "Port Hedland",
    to: "Qingdao",
    vessel: "Drava Falcon",
    departureIso: "2026-05-15T09:00:00Z",
    arrivalIso: "2026-05-30T05:45:00Z",
    distanceNm: 4170,
    status: "In transit",
    fuelTons: 1640,
    onTimeScore: 84,
    riskScore: 28
  },
  {
    id: "vy-005",
    routeCode: "ME-EU-18",
    from: "Ras Tanura",
    to: "Rotterdam",
    vessel: "Equinox Voyager",
    departureIso: "2026-05-09T07:30:00Z",
    arrivalIso: "2026-06-12T22:00:00Z",
    distanceNm: 6300,
    status: "In transit",
    fuelTons: 2110,
    onTimeScore: 52,
    riskScore: 64
  },
  {
    id: "vy-006",
    routeCode: "EU-NA-09",
    from: "Bremerhaven",
    to: "New York",
    vessel: "Glacier Tide",
    departureIso: "2026-05-18T22:00:00Z",
    arrivalIso: "2026-05-31T17:20:00Z",
    distanceNm: 3640,
    status: "In transit",
    fuelTons: 880,
    onTimeScore: 91,
    riskScore: 19
  },
  {
    id: "vy-007",
    routeCode: "AS-EU-21",
    from: "Shanghai",
    to: "Felixstowe",
    vessel: "Helios Strait",
    departureIso: "2026-05-19T13:00:00Z",
    arrivalIso: "2026-06-09T06:15:00Z",
    distanceNm: 11200,
    status: "In transit",
    fuelTons: 3120,
    onTimeScore: 87,
    riskScore: 24
  }
];

export const disruptions: Disruption[] = [
  {
    id: "d-001",
    severity: "Critical",
    type: "Congestion",
    location: "Long Beach (USLGB)",
    message: "27 vessels at anchorage. ILWU shift overtime restrictions extend dwell times beyond 60h.",
    affectedVessels: 11,
    detectedIso: "2026-05-22T05:42:00Z",
    status: "Open"
  },
  {
    id: "d-002",
    severity: "Warning",
    type: "Weather",
    location: "Port Hedland (AUPHE)",
    message: "Cyclone watch tier-2 issued. Export loading window narrows by 36-48h.",
    affectedVessels: 7,
    detectedIso: "2026-05-22T01:18:00Z",
    status: "Monitoring"
  },
  {
    id: "d-003",
    severity: "Watch",
    type: "Geopolitical",
    location: "Bab-el-Mandeb",
    message: "Insurance re-rating for Red Sea transits up 8% w/w. Two carriers reroute via Cape.",
    affectedVessels: 4,
    detectedIso: "2026-05-21T18:55:00Z",
    status: "Open"
  },
  {
    id: "d-004",
    severity: "Watch",
    type: "Strike",
    location: "Le Havre (FRLEH)",
    message: "Dock workers union vote scheduled May 28. Stoppage probability 31% per model.",
    affectedVessels: 0,
    detectedIso: "2026-05-21T15:10:00Z",
    status: "Monitoring"
  },
  {
    id: "d-005",
    severity: "Info",
    type: "Mechanical",
    location: "Suez Canal — northbound",
    message: "Convoy delayed 90 min after tug repositioning. No backlog impact expected.",
    affectedVessels: 2,
    detectedIso: "2026-05-21T09:34:00Z",
    status: "Mitigated"
  },
  {
    id: "d-006",
    severity: "Warning",
    type: "Congestion",
    location: "Singapore (SGSIN)",
    message: "Anchorage queue +12 w/w. Bunker stem windows extending past 18h.",
    affectedVessels: 6,
    detectedIso: "2026-05-20T22:01:00Z",
    status: "Open"
  }
];

export const kpis: CockpitKpis = {
  vesselsInTransit: vessels.filter((v) => v.status === "Underway").length,
  portsUnderStress: ports.filter((p) => p.congestion === "Heavy" || p.congestion === "Critical").length,
  activeDisruptions: disruptions.filter((d) => d.status !== "Mitigated").length,
  onTimeScore: Math.round(
    voyages.reduce((sum, v) => sum + v.onTimeScore, 0) / voyages.length
  ),
  avgPortWaitHours: Math.round(
    ports.reduce((sum, p) => sum + p.avgWaitHours, 0) / ports.length
  ),
  carbonIntensity: Math.round(
    vessels.reduce((sum, v) => sum + v.carbonIndex, 0) / vessels.length
  )
};
